language: php

php: 
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

before_install:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: 
     - mkdir -p build/logs
     - bin/phpunit -c phpunit.metrics.xml.dist

after_script:
    - bin/phpcs --extensions=php --standard=PSR2 src/
    - bin/phpmd src text 'codesize,controversial,design'
    - bin/phpcpd src  --progress
    - php bin/coveralls -v
